# Generated by Django 2.0.2 on 2018-03-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.AddField(
            model_name='details',
            name='age',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='c',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='female',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='male',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='parents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='passengerclass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='passengerid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='q',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='s',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='siblings',
            field=models.IntegerField(default=0),
        ),
    ]
