# Generated by Django 2.0.2 on 2018-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer', '0002_auto_20180306_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='details',
            name='c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='female',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='male',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='q',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='s',
            field=models.IntegerField(default=0),
        ),
    ]
